dots: rewrite `game-performance` script

diff --git a/dots/dot_local/bin/readonly_executable_game-performance b/dots/dot_local/bin/readonly_executable_game-performance
--- a/dots/dot_local/bin/readonly_executable_game-performance
+++ b/dots/dot_local/bin/readonly_executable_game-performance
@@ -1,25 +1,26 @@
-#!/bin/sh
+#!/bin/env bash
 
+GUARD_CMD=()
 guard() {
-    local TOOLS="$1"
+    local CMD="$1"
     shift
-    local EXEC_CHAIN=''
 
-    for TOOL in $TOOLS; do
-        if command -v "$TOOL" >/dev/null 2>&1; then
-            case "$TOOL" in
-                "gamemoderun")
-                    export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/\$LIB/libgamemode.so"
-                    ;;
-            esac
+    if ! command -v "$CMD" >/dev/null 2>&1; then
+        echo "Warning: '$CMD' not found! Skipping..."
+        return 0
+    fi
 
-            EXEC_CHAIN="$EXEC_CHAIN $TOOL"
-        else
-            echo "Warning: '$TOOL' not found! Skipping..."
-        fi
-    done
+    case "$CMD" in
+        gamemoderun)
+            export LD_PRELOAD="${LD_PRELOAD:+$LD_PRELOAD:}/usr/\$LIB/libgamemode.so"
+            ;;
+    esac
 
-    exec $EXEC_CHAIN "$@"
+    GUARD_CMD+=("$CMD" "$@")
 }
 
-guard 'gamemoderun prime-run' "$@"
+guard gamemoderun
+guard prime-run
+guard mangohud
+
+exec "${GUARD_CMD[@]}" "$@"
